/**
 * Felt-navn må matche eksakt det DroneLog API returnerer som CSV-headere,
 * slik at AviSafe edge functions kan bruke samme parseCsvToResult-mapping.
 * Se docs/dronelog-api-fields.md i AviSafe-repoet.
 */
export const DEFAULT_FIELDS = [
  "OSD.latitude",
  "OSD.longitude",
  "OSD.altitude [m]",
  "OSD.height [m]",
  "OSD.flyTime [ms]",
  "OSD.hSpeed [m/s]",
  "OSD.vSpeed [m/s]",
  "OSD.pitch [°]",
  "OSD.roll [°]",
  "OSD.directionYaw [°]",
  "OSD.gpsNum",
  "OSD.flycState",
  "BATTERY.chargeLevel [%]",
  "BATTERY.totalVoltage [V]",
  "BATTERY.current [A]",
  "BATTERY.temperature [°C]",
  "BATTERY.cellVoltage1 [V]",
  "BATTERY.cellVoltage2 [V]",
  "BATTERY.cellVoltage3 [V]",
  "BATTERY.cellVoltage4 [V]",
  "BATTERY.cellVoltage5 [V]",
  "BATTERY.cellVoltage6 [V]",
  "BATTERY.cellVoltageDeviation [V]",
  "BATTERY.maxCellVoltageDeviation [V]",
  "GIMBAL.pitch [°]",
  "GIMBAL.roll [°]",
  "GIMBAL.yaw [°]",
  "HOME.latitude",
  "HOME.longitude",
  "HOME.altitude [m]",
  "DETAILS.aircraftName",
  "DETAILS.aircraftSN",
  "DETAILS.batterySN",
  "DETAILS.fcSN",
  "DETAILS.startTime",
  "DETAILS.maxAltitude [m]",
  "DETAILS.maxHSpeed [m/s]",
  "DETAILS.maxVSpeed [m/s]",
  "DETAILS.maxDistance [m]",
  "DETAILS.totalDistance [m]",
  "DETAILS.totalTime [s]",
  "CALC.distance2D [m]",
  "CALC.distance3D [m]",
  "CALC.totalFlightTime [s]",
] as const;

export type FieldName = (typeof DEFAULT_FIELDS)[number] | string;
